# Generated by Django 3.2.3 on 2021-05-29 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210421_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone'),
        ),
    ]
